/// 需求 23 Phase B — AuthController
///
/// Single source of truth for the current user binding. Backed by
/// AuthStorage (token in secure storage, metadata in SP) and AuthApi
/// (server round-trips). Exposed to widgets via AuthScope (InheritedNotifier).
///
/// 401 handling discipline (plan v2 §6.4 / D11): on token expiry the
/// controller transitions to `tokenExpired`, retaining `currentUser` and
/// `auth_current_user_id` in storage. **Never** auto-switches to guest —
/// that's a user-visible "App ate my data" bug because drift queries
/// would suddenly mismatch the guest user_id.
///
/// Concurrency (plan v2 §6.6): `epoch` increments on every user switch.
/// In-flight API requests captured an epoch at issue; ApiClient checks
/// the controller's current epoch on response and drops stale responses.
library;

import 'package:flutter/foundation.dart';

import 'auth_api.dart';
import 'auth_storage.dart';
import 'auth_types.dart';

class AuthController extends ChangeNotifier {
  final AuthStorage storage;
  final AuthApi api;

  AuthUser? _user;
  AuthStatus _status = AuthStatus.loading;
  int _epoch = 0;

  /// Construction does NOT load state — caller must call [bootstrap].
  AuthController({required this.storage, required this.api});

  // ========== Public observable state ==========

  AuthUser? get currentUser => _user;
  AuthStatus get status => _status;
  int get epoch => _epoch;

  /// Convenience: the currently bound user_id (from storage or in-memory).
  /// Returns [AuthStorage.pendingLocalGuestUserId] only when no server-issued
  /// id is available yet (offline cold start).
  String get currentUserId =>
      _user?.id ??
      storage.readUserId() ??
      AuthStorage.pendingLocalGuestUserId;

  bool get isAuthenticated =>
      _status == AuthStatus.authedGuest ||
      _status == AuthStatus.authedRegistered;

  bool get isRegistered => _status == AuthStatus.authedRegistered;

  bool get isOfflineGuest => _status == AuthStatus.offlineGuest;

  bool get isTokenExpired => _status == AuthStatus.tokenExpired;

  // ========== Lifecycle: bootstrap (called once at app start) ==========

  /// Resolve the initial user binding from storage + network.
  ///
  /// Flow (plan v2 §7.4):
  ///   1. Read auth_current_user_id from SP.
  ///   2. If token present → GET /auth/me to verify. Success → status=authed.
  ///      Failure (401/network) → fall through to step 3.
  ///   3. POST /auth/guest(device_id) to start or re-attach a guest session.
  ///   4. Offline → keep pendingLocalGuestUserId placeholder.
  ///
  /// [deviceId] must be the device's UUID (already generated by
  /// DeviceInfoService). Network call timeout via [networkTimeout].
  Future<void> bootstrap({
    required String deviceId,
    Duration networkTimeout = const Duration(seconds: 8),
  }) async {
    _status = AuthStatus.loading;
    notifyListeners();

    final storedUserId = storage.readUserId();
    final storedToken = await storage.readToken();
    final storedAccountType = storage.readAccountType();

    // Step 1: try existing token
    if (storedToken != null && storedUserId != null) {
      try {
        final user = await api.me(token: storedToken).timeout(networkTimeout);
        _user = user;
        _status = user.accountType == AccountType.registered
            ? AuthStatus.authedRegistered
            : AuthStatus.authedGuest;
        notifyListeners();
        return;
      } on AuthApiException catch (e) {
        if (e.statusCode == 401) {
          // Server explicitly rejected the token. Clear token, surface
          // tokenExpired so UI can prompt re-login. **Keep user_id** —
          // see plan v2 §6.4: never auto-degrade to guest, otherwise
          // local drift data becomes invisible to the user.
          await storage.clearToken();
          _user = AuthUser(
            id: storedUserId,
            email: null,
            nickname: 'Learner',
            accountType: storedAccountType,
            createdAt: '',
          );
          _status = AuthStatus.tokenExpired;
          notifyListeners();
          return;
        }
        // Network / 5xx → continue offline with the stored user_id.
      } catch (_) {
        // Timeout / connectivity. Treat as offline.
      }
      // If we get here, we have storedUserId but no working token. Try a
      // guest re-attach as long as we have a token-free identity to fall
      // back to. If the user was registered, we surface tokenExpired
      // instead (re-login needed, NOT silent guest switch).
      if (storedAccountType == AccountType.registered) {
        _user = AuthUser(
          id: storedUserId,
          email: null,
          nickname: 'Learner',
          accountType: AccountType.registered,
          createdAt: '',
        );
        _status = AuthStatus.tokenExpired;
        notifyListeners();
        return;
      }
    }

    // Step 2: bring up a guest session (idempotent per device_id)
    try {
      final res = await api.guest(deviceId: deviceId).timeout(networkTimeout);
      await _commitSession(res);
      return;
    } catch (_) {
      // Step 3: offline — fall back to pending-local-guest placeholder.
      // We DO NOT write a placeholder user_id to storage; storage stays
      // empty until a real guest token is obtained. currentUserId getter
      // returns the placeholder for downstream queries.
      _user = null;
      _status = AuthStatus.offlineGuest;
      notifyListeners();
    }
  }

  // ========== Auth flows (called by UI / actions) ==========

  Future<void> register({
    required String email,
    required String password,
    String? nickname,
  }) async {
    final res = await api.register(
      email: email,
      password: password,
      nickname: nickname,
    );
    await _commitSession(res);
  }

  Future<void> login({
    required String email,
    required String password,
  }) async {
    final res = await api.login(email: email, password: password);
    await _commitSession(res);
  }

  /// Same-row bind. users.id preserved (plan v2 §6.2).
  Future<void> bindCurrentGuest({
    required String email,
    required String password,
  }) async {
    final token = await storage.readToken();
    if (token == null) {
      throw const AuthApiException(
        statusCode: 0,
        errorCode: 'NO_TOKEN',
        message: 'No active guest token to bind',
      );
    }
    final res = await api.bind(
      guestToken: token,
      email: email,
      password: password,
    );
    await _commitSession(res);
  }

  /// Log out the current user.
  ///
  /// plan v2 §6.5 / D7 discipline:
  ///   - Clear token + user_id + account_type
  ///   - **Never** touch drift / SP progress / settings — that's user
  ///     data and a re-login may restore it
  ///   - Re-enter offlineGuest state; AuthBootstrap's next run (or an
  ///     explicit guest-restart) will bring up a fresh guest session.
  Future<void> logout() async {
    final token = await storage.readToken();
    if (token != null) {
      try {
        await api.logout(token: token);
      } catch (_) {
        // Server logout is best-effort; storage clear is authoritative.
      }
    }
    await storage.clearSession();
    _user = null;
    _epoch++;
    _status = AuthStatus.offlineGuest;
    notifyListeners();
  }

  /// Marks the controller as token-expired. Called by ApiClient on 401.
  /// Idempotent — no-op if already in this state.
  Future<void> markTokenExpired() async {
    if (_status == AuthStatus.tokenExpired) return;
    await storage.clearToken();
    _status = AuthStatus.tokenExpired;
    notifyListeners();
  }

  /// Apply an /auth/* response: persist token + metadata, update state,
  /// bump epoch so any in-flight pre-switch requests get dropped.
  Future<void> _commitSession(AuthResponse res) async {
    await storage.writeToken(res.token);
    await storage.writeUserId(res.user.id);
    await storage.writeAccountType(res.user.accountType);
    _user = res.user;
    _epoch++;
    _status = res.user.accountType == AccountType.registered
        ? AuthStatus.authedRegistered
        : AuthStatus.authedGuest;
    notifyListeners();
  }
}
