-- 007_release_foundation.sql
-- v0.3.0 PR-A Day 1: 内容发布治理 schema 骨架
--
-- Purpose: 为后续 PR-A Day 2-5 的 pipeline.py 统一 entry / 状态机应用层 /
--   manifest API 实现铺路。本 migration 只动 schema + 既有数据 backfill，
--   不写 service / API 代码。App 暂不消费（v0.3 §B.12 锁定边界）。
--
-- References:
--   docs/design/词书单词例句与例句音频架构_v0.3.md  §B.4 / §B.10 / §B.12
--   apps/api/src/infrastructure/postgres/migrations/004_audio_assets_pilot.sql
--     (沿用 UP/DOWN 标记格式 + IF NOT EXISTS 幂等模式)
--
-- 评审采纳（吸收两份独立评审 8 处真改进）:
--   #1 release_id SET NOT NULL after backfill (关后门)
--   #2 status CHECK 约束 (examples + content_release，挡 typo)
--   #3 ADD CONSTRAINT 用 DROP IF EXISTS + ADD 幂等模式
--   #4 验收 SQL 条件化（空表场景）
--   #5 (plan-only) 去掉硬编码密码
--   #6 legacy.package_set 用 jsonb_agg backfill 真实 manifest id 数组
--   #7 MIN(generated_at) defensive COALESCE
--   #8 idx_examples_word_status 复合索引贴读路径
--   (#9/#10/#11 是 Day 2-5 application 层职责，本 migration 不动)
--
-- 状态机参考（v0.3 §B.4.3 / §B.4.5）:
--   examples.status:        'active' / 'deprecated' / 'deleted'
--   content_release.status: 'draft' / 'validated' / 'active' / 'deprecated' / 'revoked'
--   audio_assets.status:    新代码用 'ready' / 'superseded' / 'eligible_for_gc' /
--                           'deleted'；历史 'gc_deleted' 保留但不加 CHECK

-- UP

-- ---------- 1. examples 加 2 列 + status CHECK + 复合索引 ----------
ALTER TABLE examples ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'active';
ALTER TABLE examples ADD COLUMN IF NOT EXISTS content_hash VARCHAR(64);

-- CHECK 约束（评审采纳 #2）：挡 typo 比 enum 灵活；DROP IF EXISTS 幂等
ALTER TABLE examples DROP CONSTRAINT IF EXISTS chk_examples_status;
ALTER TABLE examples
  ADD CONSTRAINT chk_examples_status
  CHECK (status IN ('active', 'deprecated', 'deleted'));

-- 复合索引（评审采纳 #8）：贴近真实读路径 WHERE word_id=? AND status='active'
CREATE INDEX IF NOT EXISTS idx_examples_word_status ON examples(word_id, status);

-- content_hash 留 NULL；算法 Day 2 pipeline.py 定义（参考 v0.3.0 §3.4
-- canonical_json 风格，覆盖所有 package-visible 字段）

-- ---------- 2. audio_assets 加 2 列 + 既有行 backfill ----------
ALTER TABLE audio_assets ADD COLUMN IF NOT EXISTS transitioned_at TIMESTAMPTZ;
ALTER TABLE audio_assets ADD COLUMN IF NOT EXISTS transition_reason TEXT;

-- Backfill: 既有行 transitioned_at = generated_at, reason = 'initial_publish'
UPDATE audio_assets
SET transitioned_at = generated_at, transition_reason = 'initial_publish'
WHERE transitioned_at IS NULL;

-- 不加 status CHECK：历史已有 'gc_deleted'，且未来状态值还在演进

-- ---------- 3. content_release 表 (治理 SSOT) + status CHECK ----------
CREATE TABLE IF NOT EXISTS content_release (
  release_id              VARCHAR(64) PRIMARY KEY,
  title                   TEXT,
  package_set             JSONB NOT NULL DEFAULT '[]'::jsonb,
  target_min_app_version  VARCHAR(16),
  status                  VARCHAR(16) NOT NULL DEFAULT 'draft',
  rollback_target_id      VARCHAR(64) REFERENCES content_release(release_id),
  generated_by            VARCHAR(64),
  approved_by             VARCHAR(64),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  activated_at            TIMESTAMPTZ,
  revoked_at              TIMESTAMPTZ,
  activation_log          JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- status CHECK（评审采纳 #2）：5 个合法状态外的字符串拒绝
ALTER TABLE content_release DROP CONSTRAINT IF EXISTS chk_content_release_status;
ALTER TABLE content_release
  ADD CONSTRAINT chk_content_release_status
  CHECK (status IN ('draft', 'validated', 'active', 'deprecated', 'revoked'));

CREATE INDEX IF NOT EXISTS idx_content_release_status ON content_release(status);

-- 字段语义（v0.3 §B.4.5）:
--   package_set: JSONB array，例 ["examples-zk@v5","audio-meta-zk@v5"]
--                Denormalized snapshot，不是 SSOT。事实源是 content_manifest.release_id
--                Day 3 validate 子命令强制对齐两者
--   rollback_target_id: 自指 FK，指向回滚目标 release
--   approved_by: v0.3 §B.13.4 审核工作流接入点（PR-A 不实现，留位置）
--   activation_log: 状态转换审计 JSONB array of {from, to, at, reason}

-- ---------- 4. content_manifest 加 release_id FK + backfill + SET NOT NULL ----------
ALTER TABLE content_manifest ADD COLUMN IF NOT EXISTS release_id VARCHAR(64);

-- 仅在 content_manifest 非空时插 legacy 占位 release（评审采纳 #4 + #7）
-- COALESCE NOW() 兜底防 generated_at 极端 NULL 边界
INSERT INTO content_release (release_id, title, status, generated_by, created_at, activated_at)
SELECT 'legacy-pre-v0.3-pr-a',
       'Pre-PR-A legacy manifest (auto-generated by migration 007)',
       'active',
       'migration:007',
       COALESCE(MIN(generated_at), NOW()),
       COALESCE(MIN(generated_at), NOW())
FROM content_manifest
HAVING COUNT(*) > 0
ON CONFLICT (release_id) DO NOTHING;

-- 既有 manifest 行批量纳入 legacy
UPDATE content_manifest SET release_id = 'legacy-pre-v0.3-pr-a' WHERE release_id IS NULL;

-- legacy.package_set 用真实 manifest id 数组 backfill（评审采纳 #6）
-- 不再是空 []，便于排查"这个 release 包含哪些包"
UPDATE content_release
SET package_set = COALESCE(
  (SELECT jsonb_agg(id ORDER BY id)
   FROM content_manifest WHERE release_id = 'legacy-pre-v0.3-pr-a'),
  '[]'::jsonb)
WHERE release_id = 'legacy-pre-v0.3-pr-a';

-- FK 用幂等模式（评审采纳 #3）：DROP IF EXISTS + ADD，手动重跑也不炸
ALTER TABLE content_manifest DROP CONSTRAINT IF EXISTS fk_content_manifest_release_id;
ALTER TABLE content_manifest
  ADD CONSTRAINT fk_content_manifest_release_id
  FOREIGN KEY (release_id) REFERENCES content_release(release_id);

-- SET NOT NULL（评审采纳 #1）：backfill 已完成，关上后门
-- 禁止后续插 release_id IS NULL 的孤儿 manifest 行
ALTER TABLE content_manifest ALTER COLUMN release_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_content_manifest_release ON content_manifest(release_id);

-- is_active vs release.status='active' 关系（评审采纳 #11）:
--   release.status 是治理事实源（"这一批是否生效"）
--   content_manifest.is_active 是包文件级开关（"这个包文件可被 API 引用"）
--   Day 4 manifest API 必须同时满足:
--     release.status='active' AND content_manifest.is_active=true 才返回

-- DOWN

DROP INDEX IF EXISTS idx_content_manifest_release;
ALTER TABLE content_manifest DROP CONSTRAINT IF EXISTS fk_content_manifest_release_id;
ALTER TABLE content_manifest ALTER COLUMN release_id DROP NOT NULL;
ALTER TABLE content_manifest DROP COLUMN IF EXISTS release_id;

DROP INDEX IF EXISTS idx_content_release_status;
ALTER TABLE content_release DROP CONSTRAINT IF EXISTS chk_content_release_status;
DROP TABLE IF EXISTS content_release;

ALTER TABLE audio_assets DROP COLUMN IF EXISTS transition_reason;
ALTER TABLE audio_assets DROP COLUMN IF EXISTS transitioned_at;

DROP INDEX IF EXISTS idx_examples_word_status;
ALTER TABLE examples DROP CONSTRAINT IF EXISTS chk_examples_status;
ALTER TABLE examples DROP COLUMN IF EXISTS content_hash;
ALTER TABLE examples DROP COLUMN IF EXISTS status;

-- DOWN 不还原已写的 backfill 数据 —— 与 v0.3 §B.7.3 "状态推进不可逆" 一致
-- dev 环境完全回退跑 npm run db:reset
