import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart';

import '../storage/drift/app_database.dart';

/// Loads the bundled CET-4 word list from app assets into the local
/// [cached_words] drift table on first launch.
///
/// This enables fully offline-capable study and review:
/// - Study: words are served from [cached_words] without any backend call.
/// - Review: [LocalReviewQueueBuilder] already reads from [cached_words].
///
/// Asset file: assets/words/book-001.json (generated by
/// apps/api/scripts/export-cet4-json.ts from docs/db/cet4.csv).
///
/// Typical call site: main() — called once during app startup.
///   await AssetWordLoader(db: AppDatabase()).loadIfNeeded('book-001');
class AssetWordLoader {
  final AppDatabase _db;

  AssetWordLoader({required AppDatabase db}) : _db = db;

  /// Load words from the bundled asset if [cached_words] is empty for [bookId].
  ///
  /// Idempotent: if the table already has rows for this book, returns 0
  /// immediately without touching the database.
  ///
  /// Returns the number of words loaded (0 = already populated).
  Future<int> loadIfNeeded(String bookId) async {
    final count = await _getCachedCount(bookId);
    if (count > 0) return 0;
    return _loadFromAsset(bookId);
  }

  Future<int> _getCachedCount(String bookId) async {
    final result = await _db.customSelect(
      'SELECT COUNT(*) AS cnt FROM cached_words WHERE book_id = ?',
      variables: [Variable.withString(bookId)],
    ).getSingle();
    return result.read<int>('cnt');
  }

  Future<int> _loadFromAsset(String bookId) async {
    final jsonString =
        await rootBundle.loadString('assets/words/book-001.json');
    final data = json.decode(jsonString) as Map<String, dynamic>;
    final wordList = data['words'] as List<dynamic>;
    final nowMs = DateTime.now().toUtc().millisecondsSinceEpoch;

    // Batch insert all words — INSERT OR IGNORE so re-runs are safe.
    await _db.batch((batch) {
      for (final w in wordList) {
        final map = w as Map<String, dynamic>;
        batch.insert(
          _db.cachedWords,
          CachedWordsCompanion.insert(
            wordId: map['wordId'] as String,
            bookId: bookId,
            wordText: map['wordText'] as String,
            meaning: map['meaning'] as String,
            phonetic: Value(map['phonetic'] as String?),
            translation: Value(map['translation'] as String?),
            frequencyRank: Value((map['frequencyRank'] as num?)?.toInt() ?? 0),
            sortOrder: Value((map['sortOrder'] as num?)?.toInt() ?? 0),
            cachedAt: nowMs,
          ),
          mode: InsertMode.insertOrIgnore,
        );
      }
    });

    return wordList.length;
  }
}
