import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../storage/drift/app_database.dart';
import '../util/stable_id.dart' show computeExampleStableId, normalizeWord;

/// PR-B3 Day 2 v0.2 #2 (R1#2) review-adopted: injected DI replaces direct
/// `rootBundle.loadString` calls so unit tests can fake the asset layer
/// without using `setMockMessageHandler('flutter/assets')` — that channel
/// would be the first repo-wide use and risky to introduce here.
typedef AssetLoader = Future<String> Function(String path);

/// Loads a preset wordbook (ZK / GK) from bundled assets into the local
/// SQLite database on first launch.
///
/// Populated tables (all with INSERT OR IGNORE — idempotent and safe for
/// words shared across multiple books):
///   - [preset_wordbooks]       (1 row per book slug)
///   - [word_entries]           (1 row per unique word)
///   - [word_book_assignments]  (1 row per word × book pair)
///   - [example_sentences]      (N rows per word, up to 5)
///
/// Asset path: assets/words/{bookSlug}.json
///   Generated by apps/api/scripts/export-wordbook-json.ts
///
/// Typical call site: main() — called once per supported slug after
/// [AssetWordLoader] has finished.
///   await WordbookLoader(db: AppDatabase()).loadIfNeeded('zk');
///   await WordbookLoader(db: AppDatabase()).loadIfNeeded('gk');
class WordbookLoader {
  final AppDatabase _db;
  final AssetLoader _assetLoader;

  /// [assetLoader] is optional and defaults to `rootBundle.loadString`.
  /// Tests inject a fake to load JSON from in-memory strings instead of
  /// actual bundled assets (PR-B3 Day 2 v0.2 #2 R1#2 review-adopted).
  WordbookLoader({
    required AppDatabase db,
    AssetLoader? assetLoader,
  })  : _db = db,
        _assetLoader = assetLoader ?? rootBundle.loadString;

  /// Load the wordbook for [bookSlug] from its bundled asset if not yet
  /// present in [preset_wordbooks], or if the stored [content_version] differs
  /// from the JSON asset's [contentVersion].
  ///
  /// On version mismatch: drops and recreates all 4 content-layer tables, then
  /// reimports from the asset. Safe because these tables are asset-derived only.
  ///
  /// Integrity backstop (v0.3.0 P0): even when versions match, if any row in
  /// `example_sentences` is missing `stable_id` we treat the cache as
  /// corrupt and force a reimport. This catches the case where an earlier
  /// build of the same content_version imported rows BEFORE the stable_id
  /// field was wired through — bumping content_version is the canonical
  /// fix, but bumping it twice (e.g. content briefly flipped to '3' before
  /// stable_id, then back) wouldn't trigger reimport without this check.
  ///
  /// Returns the number of words imported into [word_entries] (0 = already up to date).
  Future<int> loadIfNeeded(String bookSlug) async {
    final jsonString =
        await _assetLoader('assets/words/$bookSlug.json');
    final data = json.decode(jsonString) as Map<String, dynamic>;
    final assetVersion = data['contentVersion'] as String?;

    final storedVersion = await _storedContentVersion(bookSlug);
    if (storedVersion != null && storedVersion == assetVersion) {
      // Integrity backstop — see method doc.
      if (await _exampleSentencesIntegrityOk()) {
        return 0;
      }
      debugPrint(
          '[WordbookLoader] $bookSlug: version match ($assetVersion) but '
          'example_sentences integrity check failed (null stable_id detected) '
          '— forcing reimport.');
    }

    // Either first load, version mismatch, or integrity-backstop trigger —
    // clear content tables and reimport.
    if (storedVersion != null) {
      await _clearContentTables(bookSlug);
    }
    return _loadFromData(bookSlug, data);
  }

  /// True if every row in `example_sentences` has a non-null `stable_id`.
  /// Returns true also when the table is empty (no rows = nothing to be
  /// inconsistent about; the version-mismatch path handles first load).
  Future<bool> _exampleSentencesIntegrityOk() async {
    final row = await _db
        .customSelect(
            'SELECT COUNT(*) AS missing FROM example_sentences '
            'WHERE stable_id IS NULL')
        .getSingleOrNull();
    if (row == null) return true;
    final missing = row.read<int>('missing');
    return missing == 0;
  }

  Future<String?> _storedContentVersion(String bookSlug) async {
    final result = await _db.customSelect(
      'SELECT content_version FROM preset_wordbooks WHERE slug = ?',
      variables: [Variable.withString(bookSlug)],
    ).getSingleOrNull();
    return result?.readNullable<String>('content_version');
  }

  /// PR-B3 Day 2 v0.2 #3 (R2#P1.2) review-adopted: bookSlug → manifest
  /// packageName mapping. server-side `deriveBookId` (controllers/
  /// content-manifest.controller.ts:79) emits `book_id='cet4'` for
  /// `examples-cet4` packages, but mobile WordbookLoader callers use
  /// bookSlug `'book-001'` for CET-4. Mapping converges them by the
  /// well-known `examples-` prefix on packageName.
  String _packageNameForBookSlug(String bookSlug) {
    if (bookSlug == 'book-001') return 'examples-cet4';
    return 'examples-$bookSlug';
  }

  /// PR-B3 Day 2 v0.2 #3 (R2#P1.2) review-adopted: per-book manifest
  /// existence check. Returns true iff `content_package_state` has at
  /// least one row with `package_kind='examples'` AND `package_name`
  /// matching this bookSlug — narrower than v0.1's full-table scan,
  /// avoiding cross-book false positives where installing manifest for
  /// book A would suppress D1 protection on book B's bundle upgrade.
  Future<bool> _hasManifestExamplesForBook(String bookSlug) async {
    final pkgName = _packageNameForBookSlug(bookSlug);
    final row = await _db
        .customSelect(
      "SELECT 1 AS hit FROM content_package_states "
      "WHERE package_kind = 'examples' AND package_name = ? LIMIT 1",
      variables: [Variable.withString(pkgName)],
    ).getSingleOrNull();
    return row != null;
  }

  /// Drop and recreate bundle-derived content-layer tables.
  ///
  /// PR-B3 Day 2 v0.2 D1 收口: example_sentences MAY contain manifest-
  /// installed rows (PR-B2 ContentPackageService writes them via
  /// stable_id-keyed InsertOrReplace). When the local DB has at least one
  /// content_package_state row whose `package_name` matches this bookSlug,
  /// we SKIP the unconditional `DELETE FROM example_sentences` and only
  /// remove rows with `stable_id IS NULL` — those are pre-v0.3-P0 legacy
  /// bundle rows that would otherwise trigger the integrity backstop in
  /// `loadIfNeeded` on every launch (forcing a useless reimport loop).
  ///
  /// **Side effect (v0.4 scope §1.3 implicit limit, R1#1 + R2#P1.1
  /// review-adopted):** once a book has manifest examples, bundle examples
  /// upgrades for that book are effectively suppressed. The subsequent
  /// `_loadFromData` reimport uses InsertOrIgnore on TWO unique indexes
  /// — `(word_id, sort_order)` and `stable_id` — and either collision
  /// produces a no-op. Bundle examples content updates therefore flow via
  /// server-pushed manifest packages (PackageInstaller InsertOrReplace by
  /// stable_id), not via app-upgrade + bundle JSON replacement. This is
  /// consistent with PR-B's design choice to transfer examples ownership
  /// from bundle to server-manifest. Bundle JSON only seeds fresh installs
  /// or books that never received manifest packages.
  Future<void> _clearContentTables(String bookSlug) async {
    // 3 张 bundle-only 表照旧清（manifest 不写这些）
    await _db.customStatement('DELETE FROM word_book_assignments');
    await _db.customStatement('DELETE FROM word_entries');
    await _db.customStatement('DELETE FROM preset_wordbooks');

    if (await _hasManifestExamplesForBook(bookSlug)) {
      debugPrint(
          '[WordbookLoader] $bookSlug has manifest examples; '
          'preserving non-null stable_id rows (PR-B3 D1 收口). '
          'Bundle examples upgrades for this book are now manifest-driven.');
      // 仅清 legacy null stable_id 行（避免 integrity backstop 死循环；
      // v0.2 #4 R2#P1.3 review-adopted）
      await _db.customStatement(
        'DELETE FROM example_sentences WHERE stable_id IS NULL',
      );
    } else {
      // 无 manifest 介入：行为完全等同 PR-B2 之前
      await _db.customStatement('DELETE FROM example_sentences');
    }
  }

  Future<int> _loadFromData(
      String bookSlug, Map<String, dynamic> data) async {
    final displayName = data['displayName'] as String;
    final contentVersion = data['contentVersion'] as String?;
    final wordList = data['words'] as List<dynamic>;
    final nowMs = DateTime.now().toUtc().millisecondsSinceEpoch;

    await _db.batch((batch) {
      // 1. Insert preset wordbook entry (with content_version)
      batch.insert(
        _db.presetWordbooks,
        PresetWordbooksCompanion.insert(
          slug: bookSlug,
          displayName: displayName,
          totalWords: Value(wordList.length),
          sortOrder: Value(bookSlug == 'zk' ? 0 : 1),
          contentVersion: Value(contentVersion),
        ),
        mode: InsertMode.insertOrIgnore,
      );

      for (final w in wordList) {
        final map = w as Map<String, dynamic>;
        final wordId = map['wordId'] as String;
        final examples = (map['examples'] as List<dynamic>?) ?? [];

        // 2. Insert word entry (shared across books — INSERT OR IGNORE)
        batch.insert(
          _db.wordEntries,
          WordEntriesCompanion.insert(
            wordId: wordId,
            wordText: map['wordText'] as String,
            meaning: map['meaning'] as String,
            phonetic: Value(map['phonetic'] as String?),
            translation: Value(map['translation'] as String?),
            definition: Value(map['definition'] as String?),
            frequencyRank:
                Value((map['frequencyRank'] as num?)?.toInt() ?? 0),
            wordForms: Value(map['wordForms'] as String?),
            importedAt: nowMs,
          ),
          mode: InsertMode.insertOrIgnore,
        );

        // 3. Insert word → book assignment with source_key (INSERT OR IGNORE)
        batch.insert(
          _db.wordBookAssignments,
          WordBookAssignmentsCompanion.insert(
            wordId: wordId,
            bookSlug: bookSlug,
            sortOrder: Value((map['sortOrder'] as num?)?.toInt() ?? 0),
            sourceKey: Value(map['sourceKey'] as String?),
          ),
          mode: InsertMode.insertOrIgnore,
        );

        // 4. Insert example sentences (INSERT OR IGNORE — first book wins;
        //    unique index on (word_id, sort_order) makes this truly idempotent)
        //
        // v0.3.0 P0: read `stableId` from asset JSON. Assets exported with
        // contentVersion '3'+ guarantee this field; older assets fall back
        // to compute-on-the-fly via the Dart reference impl (one-shot at
        // import time, never at runtime — DB §3.5).
        // Canonical word_id for stable_id hash input — normalize_word of wordText.
        // For single-word entries this == wordId from JSON; for multi-word phrases
        // (e.g. "give up") JSON's wordId hyphenates ("give-up") while the canonical
        // form keeps the space ("give up"). Codex pipeline uses the canonical form,
        // so we must too — otherwise fallback-computed stableId would diverge.
        final canonicalWordId =
            normalizeWord(map['wordText'] as String);
        for (final ex in examples) {
          final exMap = ex as Map<String, dynamic>;
          final en = (exMap['en'] as String?) ?? '';
          final assetStableId = exMap['stableId'] as String?;
          // Asset-supplied value is the source of truth. Fallback computes
          // on the fly only when missing (pre-v3 assets or partial data).
          final resolvedStableId = (assetStableId != null && assetStableId.isNotEmpty)
              ? assetStableId
              : computeExampleStableId(canonicalWordId, en);
          batch.insert(
            _db.exampleSentences,
            ExampleSentencesCompanion.insert(
              wordId: wordId,
              sense: (exMap['sense'] as String?) ?? '',
              en: en,
              cn: (exMap['cn'] as String?) ?? '',
              sortOrder:
                  Value((exMap['sortOrder'] as num?)?.toInt() ?? 0),
              stableId: Value(resolvedStableId),
            ),
            mode: InsertMode.insertOrIgnore,
          );
        }
      }
    });

    return wordList.length;
  }
}
